### ISSUE TITLE
Can't download the paper

### ISSUE THREAD

**Issue by RunningWei** [shionhonda/viton-gan#1]
I tried but can not download the paper on the website, could you please send me one? 
My email is cantiandi@gmail.com
Thanks a lot!

**Comment by shionhonda** [comment]
Thanks for your interest in our paper!
I apologize for any inconvenience due to the closed access.
I'll send you the paper via email.

**Comment by GrayXu** [comment]
Hi I have the same problem. I would appreciate it if you can send me on.
My email is mail@grayxu.cn.
Thx!
