### ISSUE TITLE
Apply for the paper

### ISSUE THREAD

**Issue by Zhenjiang-Liu** [shionhonda/viton-gan#2]
Now I am interested in the vitrual try-on. 
I find this paper in EG, but i can't download it.Could you send it to me?
My email is zhenjiangstan@gmail.com
Thank you!

**Comment by shionhonda** [comment]
Thanks for your interest!
I'll send you via email.

**Comment by jakubLangr** [comment]
Me too please @shionhonda james.langr@gmail.com
