### ISSUE TITLE
Paper

### ISSUE THREAD

**Issue by xuxiaochun025** [shionhonda/viton-gan#5]
I want to read the original paper,how to get the paper? thank you,Please

**Comment by xuxiaochun025** [comment]
The website is shown:The file is restricted,Could you offer me the paper

**Comment by shionhonda** [comment]
Could you give me your email address, please?
Mine: shion_honda [at] ipc.i.u-tokyo.ac.jp

**Comment by xuxiaochun025** [comment]
xuxiaochun025@gmail.com,Thank you very much
